ARG VARIANT="bookworm"
ARG RUST_LOG="atopile-jlc-parts=info"

FROM rust:slim-${VARIANT}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends sudo libpq-dev pkg-config git mold

# Create a non-root user called "user"
RUN adduser --disabled-password --gecos '' --shell /bin/bash user
RUN echo user ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/user \
    && chmod 0440 /etc/sudoers.d/user
# Set the working directory and grant permissions to the "user"
WORKDIR /app
RUN chown -R user:user /app

# Switch to the "user" and run subsequent commands as "user"
USER user

RUN cargo install cargo-watch
RUN cargo install sqlx-cli
RUN rustup component add rustfmt
COPY . .